//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilistaSeries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERO_PRODUCTO
    {
        public int IdG_P { get; set; }
        public int Fk_Genero { get; set; }
        public int Fk_Producto { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
