//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilistaSeries.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilistaseriesBaseEntities1 : DbContext
    {
        public MilistaseriesBaseEntities1()
            : base("name=MilistaseriesBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRITICA> CRITICA { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<GENERO_PRODUCTO> GENERO_PRODUCTO { get; set; }
        public virtual DbSet<LINEA_PEDIDO> LINEA_PEDIDO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<TIPO> TIPO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
