//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilistaSeries.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.CRITICA = new HashSet<CRITICA>();
            this.GENERO_PRODUCTO = new HashSet<GENERO_PRODUCTO>();
            this.LINEA_PEDIDO = new HashSet<LINEA_PEDIDO>();
        }
    
        public int IdProducto { get; set; }
        public string Titulo { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0}")]
        public decimal Anyo { get; set; }
        public int Duracion { get; set; }
        public string Pais { get; set; }
        public string Sinopsis { get; set; }
        public string Imagen { get; set; }
        public string Clasificacion { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:C}")]
        public decimal Precio { get; set; }
        public string Direccion { get; set; }
        public string licencias { get; set; }
        public string Studios { get; set; }
        public string Actores { get; set; }
        public int Fk_Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRITICA> CRITICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENERO_PRODUCTO> GENERO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEA_PEDIDO> LINEA_PEDIDO { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
